[package]
name = "squarkdown"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
lto = true
strip = true

[dependencies]
enum_stringify = "0.6.5"
glob = "0.3.4"
lazy_static = "1.5.0"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
time = { version = "0.3.55", features = ["macros", "parsing", "serde"] }
tinyvec = { version = "1.12.0", features = ["alloc", "serde"] }
toml = "1.1.4"

[lints.clippy]
partialeq_to_none = "allow"
