repo = "Squarkdown"

[paths]
site = "/site/"
sources = [
	"/",
	"/docs/",
	"/.squarkdown/content/",
]

[out]
folder = "src/routes/(docs)/(dyna)/"
file = "+page.svx"
data = "src/site.json"

[format]
preserve-comments = true
externalise-links = true

[styles]
folder = "src/styles/"
base-file = "article.scss"

[fonts]
queries = [
	"Sora:wght@100..800"
]

[errors]
on-error = "warn"
file-already-exists = "overwrite"
# linked-file-inactive = "link-to-github"
linked-file-inactive = "error"
