module Extras

require "date"


## :: &Routes -> &RepoConfig -> Result () (Error | IO)
def self.prep_scss(routes:, repo_config:)

  log "preprocessing SCSS..."

  begin
    self.try_prep_scss(routes:, repo_config:)
    log success: "preprocessed SCSS!"
  
  rescue => e
    squark_error(e, repo_config:)
  
  end
end


private

## :: &Routes -> &RepoConfig -> Result () (Error | IO)
def self.try_prep_scss(routes:, repo_config:)
  
  routes.check_site_resolved()
  
  styles_dir = routes.site / repo_config.styles.path
  raise "#{WHITE}styles / path#{RED} does not exist: #{BLUE}#{styles_dir}#{RED} does not exist" unless styles_dir.exist?

  files = styles_dir.glob("**/~*.scss")
  total = files.length

  if total == 0
    # NOTE: Non-critical, flag to user and carry on
    log error: "no SCSS files found in #{BLUE}#{styles_dir}"
  else
    log success: "found #{total} SCSS files in #{BLUE}#{styles_dir}"
  end

  data = files.each_with_index.map do |file, i|
    log_count(i+1, total:, file:)
    
    dest = file.relative_path_from(styles_dir).cleanpath.sub_ext ""

    "@use '#{dest}' as *;"
  end

  data.sort!

  text = "
/// SCSS configuration
/// Generated by Squarkdown on: #{Date.today.strftime("%d %B %Y")}

const scssConfig = {
  includePaths: [\"#{repo_config.styles.path}\"],
  prependData: `
    #{data.join("\n    ")}
  `
};
export default scssConfig;
".lstrip

  File.write(routes.site / "scss-config.js", text)
end


end
