require "date"

require_relative "../routes"
require_relative "../utils/ansi"
require_relative "../utils/log"
require_relative "../utils/error"


def prep_scss(repo_config:)
  log "preprocessing SCSS..."

  begin
    try_prep_scss(repo_config:)
  rescue => e
    squark_error(e, repo_config:)
  end
end


def try_prep_scss(repo_config:)
  partial = Pathname.new(repo_config["styles / path"])
  route = Routes.site / partial
  raise "failed to resolve #{WHITE}styles / path#{RED}: #{BLUE}#{route.to_s}#{RED} does not exist" unless route.exist?

  files = route.glob("**/~*.scss")
  total = files.length

  data = files.each_with_index.map do |file, i|
    log "#{i+1}#{GREY} of #{total}: #{WHITE}#{file.parent.basename}#{GREY}/#{BLUE}#{file.basename}"
    
    dest = file.relative_path_from(route).sub_ext ""
    "@use '#{dest}' as *;"
  end

  data.sort!

  text = """/// SCSS configuration
/// Generated by Squarkdown on: #{Date.today.strftime("%d %B %Y")}

const scssConfig = {
  includePaths: [\"#{partial}\"],
  prependData: `
    #{data.join("\n    ")}
  `
};
export default scssConfig;
"""

  File.write(Routes.site / "scss-config.js", text)
end
