name: Site

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/site.yaml'
      - 'site/package-lock.json'
      - 'npm/package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './site/'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v7

      - name: 'Setup Node'
        uses: actions/setup-node@v7
        with:
          cache: 'npm'
          cache-dependency-path: './site/package-lock.json'

      - name: '› npm ci'
        run: |
          npm ci
        # run: |
        #   npm install stranger-quarkdown@latest

      - name: '› cargo install squarkdown'
        run: |
          cargo install squarkdown --version 4.0.0-alpha.0

      - name: '› npm run buildx'
        run: |
          squarkdown --assets
          npm run build

      - name: 'Upload Artifact'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site/build/'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 'Deploy'
        id: deployment
        uses: actions/deploy-pages@v5
