name: Tests

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test.yaml'
      - 'squarkdown/tests/**'
      - 'squarkdown/Cargo.toml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
          
      - name: '› cargo test'
        run: |
          cd squarkdown
          cargo test
